### ISSUE TITLE
Question: Creating mesh with USharp

### ISSUE THREAD

**Issue by fraguada** [pixeltris/USharp#109]
Not sure if this is the appropriate place to ask a question, but I am curious if there is a way to programatically create a mesh via USharp. If I am not mistaken, there are several ways one could create a mesh with UE's API:

- [Custom Mesh Component Plugin](https://docs.unrealengine.com/en-US/API/Plugins/CustomMeshComponent/index.html)
- [Procedural Mesh Component](https://docs.unrealengine.com/en-US/API/Plugins/ProceduralMeshComponent/index.html)
- Blueprint versions of the above
- [Create Static Mesh](https://docs.unrealengine.com/en-US/API/Editor/UnrealEd/CreateStaticMesh/index.html)
- [RawMesh](https://docs.unrealengine.com/en-US/API/Developer/RawMesh/FRawMesh/index.html)

I'm looking for a way to create a mesh programmatically via USharp and I'm obviously missing some key lessons in how meshes work within UE. Is it possible to create a mesh from USharp and have it added to the scene either during editing or in game play? If so, can anyone point me in the right direction?

**Comment by pixeltris** [comment]
I briefly looked at this before. Doing it properly probably involves writing manual bindings / wrappers for the various native functions / structs used to create the meshes. This may be slightly problematic with marshalling.

So to answer the question; no there currently isn't an easy way to do this unless the Blueprint bindings are already generated correctly for USharp (in which case that might work).

**Comment by fraguada** [comment]
> unless the Blueprint bindings are already generated correctly for USharp (in which case that might work).

How would I determine if this is the case? I tested creating a mesh via a blueprint, directly in the editor, and that works of course. 

Can I access an actor's blueprint from USharp and feed the CreateMeshSection node with the vertex/face data?

**Comment by fraguada** [comment]
I was able to create a class that was `Blueprintable` and have that have a `ProceduralMeshComponent`. The class has a few lists for vertices and face IDs (which I populate from my code that is reading them from elsewhere) which can be retrieved and fed into a `CreateMeshSection` node in the blueprint editor.
That is enough to get me going for now! Feel free to close this issue.
