### ISSUE TITLE
Create an automated GameSolution.sln generator step

### ISSUE THREAD

**Issue by RobertAcksel** [pixeltris/USharp#16]
Project looks promising. :+1:
To me it looks like you choose to do the heavy lifting in the managed code. Which is the best choice from my point of view. 

From what i have seen so far there is no automated GameSolution.sln generator step at the moment. 
Is this correct???
I think it needs to be build soon to speed up the progress of the project. Is there anything going on here. 
If not lets talk about the strategy to build one.

I suggest the following steps:
- Add a sln generation step in the c# codebase (UnrealEngine.Runtime).
- Add one template version of the solution/project needed when building a game dll to the repository containing the bare minimum example of c# code and all necessary settings including the post process steps.
- Add c# MSBuild SDK files to support MSBuild environment variables to the project file and a minimum project configuration to the project. It will contain the configuration including output path and post process steps as well as defines and anything we might need.
It is easy to read and write and will enable us to generate VS settings without the need to modify the project/solution template at all. (do not over complicate it with an SDK resolver or other complicated stuff until it is definitive necessary. keep it simple and effective)
- Add unit test so we know when it breaks.

Maybe that i can help building it (since i have a bare minimum concept in place)!

**Comment by pixeltris** [comment]
Yea no work has been done on something like this yet but it is definitely needed for ease of use. Your proposed setup sounds great. I've never touched MSBuild SDK stuff so any concept related things for that would be great.

I'm personally not going to look into this until the project is in a semi-usable state but any contributions are welcomed. (Semi-usable is still some way off yet if that isn't clear in the readme - I'll maybe make a list of things I still have to do to get it to a similar state as mono-ue).
