### ISSUE TITLE
Editor does not pick up the game.dll when it is build the first time

### ISSUE THREAD

**Issue by RobertAcksel** [pixeltris/USharp#22]
hot reloading does not work when the editor was started the first time with plugin active but no game assemblie has being build yet and is build later on. only restarting the editor works for now.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/USharp/blob/bad0a69c672f5687a67ab1374fe63239e16c6ac1/Managed/UnrealEngine.Runtime/UnrealEngine.Runtime/Native/NativeFunctions.cs#L257 assemblyPaths.Add(gameAssemblyFileName); is only called if the assembly is found (this is done on first load as noted) and therefore isn't added to the list of paths to watch for file changes. Could possibly put an assembly watcher for each possible location where it is assigning and checking the path of gameAssemblyFileName.

**Comment by pixeltris** [comment]
This should be fixed. Though the error might still present itself in a debug game build depending on how the folders are structured for debug game (and if hotreload is even possible in debug game).
