### ISSUE TITLE
UnrealEngine.Runtime has a reference to envdte

### ISSUE THREAD

**Issue by RobertAcksel** [pixeltris/USharp#25]
UnrealEngine.Runtime has a reverence to envdte
this will not be resolved at runntime on many platfromrs ofc.

I propose to add an editor only assemlby which is loaded only in the editor and is not there at runntime.
![image](https://user-images.githubusercontent.com/20187182/46570317-7e6f4700-c962-11e8-860a-d1c2cb05dd25.png)

UnrealEngine.Runtime should have only the bare minimum to run USharp at runntime on board.

**Comment by pixeltris** [comment]
envdte has been removed for now. Something similar may be re-added in the future which can work properly multiple platforms.
