### ISSUE TITLE
No way to Broadcast FMulticastDelegates

### ISSUE THREAD

**Issue by Tanner555** [pixeltris/USharp#41]
There was a great example of how to create a blueprint callable FMulticastDelegate in the examples section. Unfortunately you can't call this FMulticastDelegate in c#. That's because there is currently no Broadcast binding in the generated class. I'm sure it's easy enough calling it from blueprints, but I should be able to call it from c# just as easily. 

```
public class GeneralDelegateHandler : FMulticastDelegate<GeneralDelegateHandler.Signature>
{
    public delegate void Signature();
}

[UProperty(PropFlags.BlueprintCallable | PropFlags.BlueprintAssignable), EditAnywhere, BlueprintReadWrite]
public GeneralDelegateHandler BowlTurnIsFinished { get; set; }
```

I currently just use c# events and delegates, but that would be nice if there was a c# binding for Broadcast. I don't think this would work.

```
if (BowlTurnIsFinished.IsBound)
{
    BowlTurnIsFinished.Invoke();
}
```

Maybe it would, I haven't tried it. Someone can comment if they found a way to broadcast from c#.

**Comment by Tanner555** [comment]
Funny thing is the Invoke method seems to work just fine with multicast delegates. Any method I bind has to be a ufunction, and I have to unbind once the game ends (otherwise I get a nasty error on restart). I still think there should be a Broadcast binding, but using Invoke() works perfectly.

**Comment by pixeltris** [comment]
Invoke is the same as Broadcast yea. Not sure if adding a "Broadcast" wrapper is any more intuitive seeing as the C++ calls it "Execute". The target functions have to be UFunction as they are designed to work with Unreal (Unreal can't work with functions it doesn't know about).

>I have to unbind once the game ends (otherwise I get a nasty error on restart)

That sounds pretty bad. I assume thats an issue with PIE. Currently USharp recreated delegates on hotreload but not on PIE. It sounds like it should be doing that.
