### ISSUE TITLE
Can't set PrimaryComponentTick.CanEverTick because it is a struct

### ISSUE THREAD

**Issue by iainmckay** [pixeltris/USharp#61]
Ticking can't be turned off because PrimaryComponentTick is a struct.

**Comment by pixeltris** [comment]
FTickFunction which is used by AActor.PrimaryActorTick and UActorComponent:PrimaryComponentTick is currently a struct as mentioned. This may change in the future to be a class. It was designed to be a struct to avoid an additional C# object from being created per actor/component.

It can be modified by creating a local variable (this is essentially just a pointer):

```
FTickFunction tick = TickPrimaryComponentTick;
tick.CanEverTick = true;
```

It may be changed to a class in the future and may also be a pooled class which is returned to the pool once an actor / component is destroyed. This would ensure that there wouldn't be any GC overhead but there would still be the overhead of the cached FTickFunction instance in each AActor / UActorComponent.
