### ISSUE TITLE
Managed dll files not generating

### ISSUE THREAD

**Issue by dagillespie** [pixeltris/USharp#69]
Can't resolve UnrealEngine.Runtime.dll / UnrealEngine.dll references when Editor opens after running PluginInstaller steps in wiki:

- PluginInstaller type the buildcpp command to compile the C++ code
- In PluginInstaller type the copyruntime all

Not possible to add references to  /USharp/Binaries/Managed as no folder is created from above steps. It may be that simply clarifying the steps in the wiki will help resolve this.

**Comment by pixeltris** [comment]
/USharp/Binaries/Managed should exist as that is where PluginInstaller/UnrealEngine.Runtime.dll should be located after building those two projects.

If you didn't build UnrealEngine.Runtime an error will pop up saying "Couldn't find the assembly file: 'UnrealEngine.Runtime.dll'"

UnrealEngine.dll wont exist until you run the `SharpGen modules` command followed by the `USharpGen compile` command (in the ue4 console command prompt). I think the `USharpGen compile` command currently will only be successful if VS2017 is installed. VS2019 needs to be looked at.

**Comment by dagillespie** [comment]
Thanks - looks like the issue was on my side. The files appear there now. Marking as closed.
