### ISSUE TITLE
AActor HelloWorld Example documentation

### ISSUE THREAD

**Issue by dagillespie** [pixeltris/USharp#70]
Documentation on a simple helloWorld application using AActors would be useful in the wiki under "writing c# game code" would be very welcome. Please close this item if you feel this is irrelevant to current development.

**Comment by Tanner555** [comment]
I totally agree, that would be nice. Inside the Managed folder, you should see a sample Actor class in your project. I've also created a small bowling game using USharp https://github.com/Tanner555/BowlingGameInUSharp. I've mostly used components, but you should get a good grasp at how to work with USharp after looking at the Managed source code.

**Comment by dagillespie** [comment]
Thanks. May be wrong but that base class is a UObject rather than AActor in test.cs. Will have a look at the bowling game for reference.

**Comment by Tanner555** [comment]
I think you're right. But you should easily be able to create an AActor in a similar manner. One thing you should be wary of is overriding certain methods won't work in C# without modifying your blueprint class. Override like normal, then in your blueprint class, generate the method you are overriding. Right click on the node, and press the dropdown that says something about the Parent Method.

**Comment by dagillespie** [comment]
Deconstructing a simple example has been awesome as it's really easy to add actor components to actors exposing C# functionality. If you're longer term thinking about usability then some boiler plate code, much like what UE4 generates when you generate a C++ class so someone can get into event calls like tick etc would be awesome.

**Comment by pixeltris** [comment]
I'm currently working on converting some of the blueprint templates to C# which should cover some of the basics like setting up actors, dealing with input, tick, and such.

Adding some 'getting started' code snippets to the wiki is a good idea so I'll have a look at after the templates are finished.

**Comment by dagillespie** [comment]
That is awesome - this would really help people get started. Am really impressed by this plugin as it's adding some much deserved interoperability with C# that a lot of people have been asking for!

**Comment by pixeltris** [comment]
I added a basic puzzle template (copied from the Blueprint puzzle template) in this commit https://github.com/pixeltris/USharp/commit/e055d283337a7a5c46126d2e4340919427bd31e9. This can be created via the regular UE4 new project dialog under the new "C#" tab. (this commit included some structural changes so existing C# projects may fail to load / compile).

I will be adding a "sandbox"/"snippets" template soon which I will modify over time as a central hub for various code snippets useful for learning how to use USharp.

**Comment by dagillespie** [comment]
Awesome - will be testing the puzzle template based on the latest commit on 4.22.1

**Comment by pixeltris** [comment]
There are now some basic AActor snippets here https://github.com/pixeltris/USharp/wiki/Actors-and-components.
