### ISSUE TITLE
Generating C# wrapper functionality for Datasmith

### ISSUE THREAD

**Issue by dagillespie** [pixeltris/USharp#71]
C# wrapper generation when running USharpGen modules errors when Datasmith plugins from Epic are enabled. Probably low on the to-do list as it's an additional Epic plugin however you may want to consider for any users utilising these Unreal Studio plugins.

Workaround is not to use datasmith with USharp!

**Comment by pixeltris** [comment]
Yea there needs to be a way of blacklisting / whitelisting modules. Maybe I'll change the `USharpGen modules` command to only generate code for a predefined whitelist and then add an additional command `USharpGen allmodules` or something to generate it everything.

**Comment by Tanner555** [comment]
Yeah that's a good idea. I think having a simple text file where you could blacklist files would be great. Similar to the text file for USharp packaging.

**Comment by dagillespie** [comment]
Whitelisting/blacklisting would be ideal as that would give a good workaround for working with any custom plugins.

**Comment by pixeltris** [comment]
Added whitelist support in https://github.com/pixeltris/USharp/commit/e055d283337a7a5c46126d2e4340919427bd31e9. The currently whitelisted modules can be found [here](https://github.com/pixeltris/USharp/blob/master/Settings/ModulesWhitelist.txt)
