### ISSUE TITLE
[Feature Request] Add Ability To Generate C# Project For Projects Not Using Templates

### ISSUE THREAD

**Issue by Tanner555** [pixeltris/USharp#75]
Before the new templates update, USharp would automatically add a Managed Folder to your project when you had the plugin enabled. Now it seems like the plugin is enabled by default, and 2 new C# starter templates have been added. But for those who want to add C# Code to an existing project (that hasn't been added to yet), it'll be a big hassle for them. I'd suggest creating a USharp command that'll generate all the needed files and put them into a Managed folder, just like before. This will make life a lot easier for those who want to add USharp to an existing project.

**Comment by demonixis** [comment]
I agree

**Comment by pixeltris** [comment]
What do you think would be better:

1) Enable USharp in the project settings (editor restart is required), when loading USharp detects that the C# sln file doesn't exist. It prompts a dialog to generate it (this prompt will be shown any time it fails to detect the C# sln file).

2) Enable USharp in the project settings (editor restart is required), a command `USharpGen project` must be typed into the UE4 command box to generate the C# sln file.

**Comment by demonixis** [comment]
The first one is better for users. However the second point is fine too.

**Comment by Tanner555** [comment]
I think the first option would be the best. Hopefully that means USharp will still be installed by default, so that C# templates will show up in the new project window. The second option is what I was originally thinking.

**Comment by pixeltris** [comment]
Implemented in https://github.com/pixeltris/USharp/commit/ea5ec40afc35606d145b5429eec09bc9b054aa7b. It prompt to copy from the TP_Blank template if no C# game code exists and USharp is enabled (this prompt will be shown when your project is loaded, after you enable USharp in your project settings).

**Comment by dagillespie** [comment]
Has this been implemented? I'm finding that when I enable USharp and restart the editor, I'm not prompted to generate C# code, despite the plugin appearing enabled. In addition, the console commands don't allow me to generate any code either.

**Comment by pixeltris** [comment]
The plugin itself is set to always be enabled. There is an additional checkbox under your project settings to enable USharp on an existing non C# project, see https://github.com/pixeltris/USharp/wiki/Plugin-Setup#adding-c-to-an-existing-project

**Comment by dagillespie** [comment]
Thanks - that's what I tried however it's not working. The steps I'm doing are the following:
- Create New Basic Code C++ Project
- USharp comes in enabled on the project by default
- No USharp console commands are available
- So I untick enabled and restart UE4 (as UE4 prompts)
- No USharp console commands are available (as expected)
- So tick enabled and restart UE4 (as UE4 prompts)
- No USharp console commands are available (not expected)

**Comment by pixeltris** [comment]
It sounds like you're using the plugin checkbox. There should be a separate checbox in "Edit->Project Settings...". The USharp commands are only available when you enable the checkbox in that section.

**Comment by dagillespie** [comment]
Apologies - yes I was.  I should have read your very clear instructions on this rather than skimmed and assumed you were simply referring to enabling the plugin from the plugins menu. It's now working fine.
