### ISSUE TITLE
VTableHacks on Mac / Linux

### ISSUE THREAD

**Issue by pixeltris** [pixeltris/USharp#76]
Currently there are a few hacks in place to swap out vtable function entries to override native C++ functions without having USharp depend on engine modifications.

On Mac the vtable swap works but calling the original function results in a crash (`this` pointer is passed in via RDX when we call the original function, but it expects it to be in RDI (at least for AActor::BeginPlay()).

Is there something wrong with the way the original function is being called? If not then the vtable hacks cannot be used as they don't work as expected. Engine modifications would be the only alternative route.

```
typedef void (UObject::*ActorBeginPlayFunc)();
CSEXPORT void CSCONV Export_VTableHacks_CallOriginal_ActorBeginPlay(ActorBeginPlayFunc Func, UObject* Obj)
{
	(Obj->*Func)();// "Obj" is passed in via RDX, the target function expects RDI
}
```

EDIT:

After doing some tests in Compiler Explorer (https://godbolt.org/) with gcc/clang, they both seem to set up the registers as expected. Xcode's disassembly view where it crashes seems to chop off instructions prior to those in the stack trace, so I was assuming it was passing by RDX based on the register values from `register read`.

The following is some code which *should* work in UE4 based on the disassembly in the main 3 compilers (gcc, clang, msvc) which can be tested on https://godbolt.org/.

```
#include <iostream>
using namespace std;

class UObject
{
public:
    int Val1;
    int Val2;
};

class AActor : public UObject
{
public:
    virtual void BeginPlay()
    {
        cout << "AActor " << Val1 << " " << Val2 << "\n";
    }
};

class ASomeActor : public AActor
{
public:
    virtual void BeginPlay() override
    {
        cout << "ASomeActor " << Val1 << " " << Val2 << "\n";
    }
};

typedef void (AActor::*ActorBeginPlayFunc)();
void Export_VTableHacks_CallOriginal_ActorBeginPlay(ActorBeginPlayFunc Func, AActor* Obj)
{
    (Obj->*Func)();
}

int main()
{
    AActor obj = ASomeActor();
    obj.BeginPlay();

    Export_VTableHacks_CallOriginal_ActorBeginPlay(&AActor::BeginPlay, &obj);

    return 0;
}
```

**Comment by pixeltris** [comment]
Fixed in https://github.com/pixeltris/USharp/commit/19120d64b3a0be40ad51c7a29d16197c87153c97 (only tested Mac). The C++ invoker was moved to C#, using the ThisCall calling convention. I can't think of any logical reason why the C++ code doesn't work as expected. There will likely be other similar issues related to VTableHacks.... possibly look at submitting engine PRs (probably futile as they will likely get rejected due to not being useful for anything other than supporting USharp).

**Comment by Tanner555** [comment]
You should make a few PRs anyways. MHutch was actually able to get several of her PRs accepted even though she barely explained what their purpose was. I'd recommend testing it out first of course :joy:

**Comment by Darkkitten** [comment]
Not sure if this fits here or not, but with 4.23
 Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: .config/USharp/Build/HostProject/Plugins/USharp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/USharp/Module.USharp.cpp.o: in function `FActorComponentTickFunction::FActorComponentTickFunction()':
Engine/Source/Runtime/Engine/Classes/Engine/EngineBaseTypes.h:461: undefined reference to `vtable for FActorComponentTickFunction'
Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: .config/USharp/Build/HostProject/Plugins/USharp/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/USharp/Module.USharp.cpp.o: in function `FActorTickFunction::FActorTickFunction()':
 Engine/Source/Runtime/Engine/Classes/Engine/EngineBaseTypes.h:428: undefined reference to `vtable for FActorTickFunction'
