### ISSUE TITLE
FRotator is pitch, yaw, roll vs pitch, roll, yaw

### ISSUE THREAD

**Issue by demonixis** [pixeltris/USharp#77]
The FRotator implementation uses the pitch, yaw, roll order instead of pitch, roll and yaw. We need to change this order to fit UE4's API.

**Comment by pixeltris** [comment]
I tried to copy the C++ math API as closely as possible. The C++ API uses pitch, yaw, roll. The implementation was copied from https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Source/Runtime/Core/Public/Math/Rotator.h

**Comment by demonixis** [comment]
OK, I said that because it's not the case in blueprint, so it's not an issue sorry.

**Comment by pixeltris** [comment]
Yea it certainly threw me off too. But it probably is best to keep to the C++ API.

**Comment by demonixis** [comment]
I agree, that's why I closed the issue. I'm more experienced with blueprint that's why it shocked me ;) 
To be honest I prefer the C++ notation
