### ISSUE TITLE
Support for default values on C# auto properties exposed to UE4

### ISSUE THREAD

**Issue by pixeltris** [pixeltris/USharp#79]
Part of the AssemblyRewriter process is rewriting the IL to remove the C# backing field for properties and instead read / write to the native memory of the underlying UE4 object. This breaks default values as the C# compiler will generate code to directly assign the backing field in the constructor.

AssemblyRewriter needs to scan the constructor to any assignments to backing fields, then take the value and generate code in the `Initialize` method to do that assignment instead.

```[UClass, Blueprintable, BlueprintType]
public class Test : AActor
{
    [UProperty, EditAnywhere]
    public int MyValue { get; set; } = 100;
}
```

**Comment by Algorithman** [comment]
Bytecode comparison for ldarg0, call?
Anything before that should be defaultvalue code, right?
