### ISSUE TITLE
UUserWidget -> GetWidgetFromName implementation?

### ISSUE THREAD

**Issue by jesst3r** [pixeltris/USharp#89]
First off, i'd like to say thank you so much for your work!
Started working with UserWidget, and it seems there are no GetWidgetFromName implementation (https://api.unrealengine.com/INT/API/Runtime/UMG/Blueprint/UUserWidget/GetWidgetFromName/index.html). Is there any alternative, maybe?
PS.: Do you accepting donates? I'd like to support you:)

**Comment by pixeltris** [comment]
Most of USharp's bindings are automatically generated by UFUNCTION/UPROPERTY exposed members. Functions which aren't tagged in this way need to be exposed to USharp manually.

https://github.com/pixeltris/USharp/pull/88/files this PR shows an example of exposing UActorComponent::RegisterComponent manually. UUserWidget::GetWidgetFromName will likely need to be exposed in the same way. I can do this for you if you want, or if you want to try it yourself I'll accept PRs for pretty much anything that you want to manually expose.
