### ISSUE TITLE
Full dev integration

### ISSUE THREAD

**Issue by dagillespie** [pixeltris/USharp#95]
This isn't likely to be the best place to put this so feel free to change this as needs be. 

I could see that this plugin may have a lot of wider community benefits. To that end, Epic might support its further development under their Megagrants - particularly where it may be in their interest to encourage C# integration to encourage engine adoption with developers familiar with Unity. They may also be able to offer direct dev support as part of this.
https://www.unrealengine.com/en-US/megagrants

**Comment by pixeltris** [comment]
There are still many areas where USharp needs improvement, it's current state should be seen as experimental (which is one reason why it hasn't been submitted as a marketplace asset yet). Unfortunately I don't think applying to megagrants would do much at this point.

[Epic / Agog Labs](https://www.unrealengine.com/en-US/blog/agog-labs-joins-epic-games) are also working on a scripting solution internally, so it would be best to see what comes of that as it may make USharp unnecessary.

**Comment by goldngood** [comment]
Does this project have a better way of communication ? I have some questions and i don't want to ask in Issues .

**Comment by pixeltris** [comment]
https://gitter.im/USharp/Lobby you can sign in with your github account.

**Comment by dagillespie** [comment]
> There are still many areas where USharp needs improvement, its current state should be seen as experimental (which is one reason why it hasn't been submitted as a marketplace asset yet). Unfortunately I don't think applying to megagrants would do much at this point.
> 
> [Epic / Agog Labs](https://www.unrealengine.com/en-US/blog/agog-labs-joins-epic-games) are also working on a scripting solution internally, so it would be best to see what comes of that as it may make USharp unnecessary.

Fair point - it may increase your quality of life whilst developing this - they may be interested in fostering this project rather than developing it in-house!
